name: Bunkai SCA

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  bunkai:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Bunkai
        uses: lesis-lat/bunkai@0.0.5
        with:
          project-path: .
          sarif-output: bunkai-results.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: bunkai-results.sarif
